services:
  notioos:
    image: ghcr.io/bobbobinson007/notioos:main
    container_name: notioos-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./db:/app/db
      - ./public:/app/public
    networks:
      - notioos-network

networks:
  notioos-network:
    driver: bridge
